### ISSUE TITLE
If you can't serialise a crate it should warn but skip it rather than panic.

### ISSUE THREAD

**Issue by gilescope** [hkmatsumoto/roogle#4]
If you can't serialise a crate it should warn but skip it rather than panic.

   Compiling roogle-api v0.1.0 (/home/gilescope/git/roogle/roogle-api)
    Finished release [optimized] target(s) in 6.47s
     Running `target/release/roogle-api`
thread 'main' panicked at 'failed to deserialize: Error("invalid type: map, expected unit", line: 1, column: 7576)', roogle-api/src/main.rs:43:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: roogle_api::krates

**Comment by gilescope** [comment]
FYI it was the backtrace.json from the top 100 crates it had trouble deserialising.

**Comment by gilescope** [comment]
For now I turned the map into a filter_map to get past that:
```
        .filter_map(|entry| {
            let json = std::fs::read_to_string(entry.path()).expect("failed to read file");
            let mut deserializer = serde_json::Deserializer::from_str(&json);
            deserializer.disable_recursion_limit();
            Crate::deserialize(&mut deserializer).ok()
        })
```
